### ISSUE TITLE
Release 2024

### ISSUE THREAD

**Issue by 22388o** [AreaLayer/FireBolt#10]
With features:

-LN

-On-chain

-PayJoin

-Nostr backup

Later will be released CoinJoin

TODO

- [x] PayJoin
- [x] LND
- [x] Coinjoin
- [x] LN/On-Chain
- [x] Nostr/Hypercore/TBD backup
- [x] Release app beta testnet
